"""Fix ine_valid_until type

Revision ID: 1b0818ad442c
Revises: 60826012ac9d
Create Date: 2025-11-10 18:13:00.156996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1b0818ad442c'
down_revision: Union[str, None] = '60826012ac9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatepersonalinfo', 'ine_valid_until',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatepersonalinfo', 'ine_valid_until',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=4),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
