"""create MunicipalCandidacy table

Revision ID: 5540656e2016
Revises: 67d12eb2b01f
Create Date: 2025-10-14 22:30:23.121442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5540656e2016'
down_revision: Union[str, None] = '67d12eb2b01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalcandidacy',
    sa.Column('political_position', sa.Enum('presidente', 'sindico', 'regidor', name='politicalposition'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('municipality', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipalcandidacy')
    # ### end Alembic commands ###
