"""create Documents table

Revision ID: 60826012ac9d
Revises: 4e9c576684c6
Create Date: 2025-11-08 20:47:54.726837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '60826012ac9d'
down_revision: Union[str, None] = '4e9c576684c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('acta_de_nacimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formato_3_de_3_contra_la_violencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formulario_de_aceptación_de_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ine_certificada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('municipal_candidacy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipal_candidacy_id'], ['municipalcandidacy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipal_candidacy_id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
