"""add fields to CandidatePersonalInfo: isPublicServant, ocupation

Revision ID: ad7ad684f483
Revises: cfaf45a8f9d8
Create Date: 2025-10-30 17:30:13.840264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ad7ad684f483'
down_revision: Union[str, None] = 'cfaf45a8f9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatepersonalinfo', sa.Column('is_public_servant', sa.Boolean(), nullable=False))
    op.add_column('candidatepersonalinfo', sa.Column('ocupation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidatepersonalinfo', 'ocupation')
    op.drop_column('candidatepersonalinfo', 'is_public_servant')
    # ### end Alembic commands ###
