"""create table CandidatePersonalInfo

Revision ID: cfaf45a8f9d8
Revises: 5540656e2016
Create Date: 2025-10-15 18:51:14.866020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cfaf45a8f9d8'
down_revision: Union[str, None] = '5540656e2016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatepersonalinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'H', name='genderenum'), nullable=False),
    sa.Column('state_of_residence', sa.Integer(), nullable=False),
    sa.Column('municipality_of_residence', sa.Integer(), nullable=False),
    sa.Column('curp', sqlmodel.sql.sqltypes.AutoString(length=18), nullable=False),
    sa.Column('ine_valid_until', sa.Date(), nullable=False),
    sa.Column('ine_clave_elector', sqlmodel.sql.sqltypes.AutoString(length=18), nullable=False),
    sa.Column('municipal_candidacy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipal_candidacy_id'], ['municipalcandidacy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipal_candidacy_id')
    )
    op.create_index(op.f('ix_candidatepersonalinfo_id'), 'candidatepersonalinfo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatepersonalinfo_id'), table_name='candidatepersonalinfo')
    op.drop_table('candidatepersonalinfo')
    # ### end Alembic commands ###
