// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_ocr_ocr_endpointSchema = {
    properties: {
        file: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'Body_ocr-ocr_endpoint'
} as const;

export const CandidacyPublicWithPersonalInfoSchema = {
    properties: {
        political_position: {
            '$ref': '#/components/schemas/PoliticalPosition'
        },
        position: {
            type: 'integer',
            maximum: 12,
            exclusiveMinimum: 0,
            title: 'Position'
        },
        municipality: {
            type: 'integer',
            maximum: 125,
            minimum: 1,
            title: 'Municipality'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        candidate_personal_info: {
            '$ref': '#/components/schemas/CandidatePersonalInfoPublic'
        }
    },
    type: 'object',
    required: ['political_position', 'position', 'municipality', 'id', 'candidate_personal_info'],
    title: 'CandidacyPublicWithPersonalInfo'
} as const;

export const CandidacyWithPersonalInfoCreateSchema = {
    properties: {
        municipal_candidacy: {
            '$ref': '#/components/schemas/MunicipalCandidacyBase'
        },
        candidate_personal_info: {
            '$ref': '#/components/schemas/CandidatePersonalInfoBase'
        }
    },
    type: 'object',
    required: ['municipal_candidacy', 'candidate_personal_info'],
    title: 'CandidacyWithPersonalInfoCreate'
} as const;

export const CandidatePersonalInfoBaseSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        birthdate: {
            type: 'string',
            format: 'date',
            title: 'Birthdate'
        },
        gender: {
            '$ref': '#/components/schemas/genderEnum'
        },
        state_of_residence: {
            type: 'integer',
            maximum: 32,
            minimum: 1,
            title: 'State Of Residence'
        },
        municipality_of_residence: {
            type: 'integer',
            maximum: 125,
            minimum: 1,
            title: 'Municipality Of Residence'
        },
        curp: {
            type: 'string',
            maxLength: 18,
            minLength: 18,
            title: 'Curp'
        },
        ine_valid_until: {
            type: 'string',
            format: 'date',
            title: 'Ine Valid Until'
        },
        ine_clave_elector: {
            type: 'string',
            maxLength: 18,
            minLength: 18,
            title: 'Ine Clave Elector'
        },
        is_public_servant: {
            type: 'boolean',
            title: 'Is Public Servant'
        },
        ocupation: {
            type: 'string',
            maxLength: 255,
            title: 'Ocupation'
        }
    },
    type: 'object',
    required: ['full_name', 'birthdate', 'gender', 'state_of_residence', 'municipality_of_residence', 'curp', 'ine_valid_until', 'ine_clave_elector', 'is_public_servant', 'ocupation'],
    title: 'CandidatePersonalInfoBase'
} as const;

export const CandidatePersonalInfoPublicSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        birthdate: {
            type: 'string',
            format: 'date',
            title: 'Birthdate'
        },
        gender: {
            '$ref': '#/components/schemas/genderEnum'
        },
        state_of_residence: {
            type: 'integer',
            maximum: 32,
            minimum: 1,
            title: 'State Of Residence'
        },
        municipality_of_residence: {
            type: 'integer',
            maximum: 125,
            minimum: 1,
            title: 'Municipality Of Residence'
        },
        curp: {
            type: 'string',
            maxLength: 18,
            minLength: 18,
            title: 'Curp'
        },
        ine_valid_until: {
            type: 'string',
            format: 'date',
            title: 'Ine Valid Until'
        },
        ine_clave_elector: {
            type: 'string',
            maxLength: 18,
            minLength: 18,
            title: 'Ine Clave Elector'
        },
        is_public_servant: {
            type: 'boolean',
            title: 'Is Public Servant'
        },
        ocupation: {
            type: 'string',
            maxLength: 255,
            title: 'Ocupation'
        }
    },
    type: 'object',
    required: ['full_name', 'birthdate', 'gender', 'state_of_residence', 'municipality_of_residence', 'curp', 'ine_valid_until', 'ine_clave_elector', 'is_public_servant', 'ocupation'],
    title: 'CandidatePersonalInfoPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MunicipalCandidacyBaseSchema = {
    properties: {
        political_position: {
            '$ref': '#/components/schemas/PoliticalPosition'
        },
        position: {
            type: 'integer',
            maximum: 12,
            exclusiveMinimum: 0,
            title: 'Position'
        },
        municipality: {
            type: 'integer',
            maximum: 125,
            minimum: 1,
            title: 'Municipality'
        }
    },
    type: 'object',
    required: ['political_position', 'position', 'municipality'],
    title: 'MunicipalCandidacyBase'
} as const;

export const PoliticalPartiesSchema = {
    type: 'string',
    enum: ['MC', 'MORENA', 'PAN', 'PRD', 'PRI', 'PT'],
    title: 'PoliticalParties'
} as const;

export const PoliticalPositionSchema = {
    type: 'string',
    enum: ['Presidente', 'Sindico', 'Regidor'],
    title: 'PoliticalPosition'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        political_party: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PoliticalParties'
                },
                {
                    type: 'null'
                }
            ]
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        municipality: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 125,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Municipality'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        political_party: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PoliticalParties'
                },
                {
                    type: 'null'
                }
            ]
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        municipality: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 125,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Municipality'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        political_party: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PoliticalParties'
                },
                {
                    type: 'null'
                }
            ]
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        municipality: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 125,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Municipality'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const genderEnumSchema = {
    type: 'string',
    enum: ['M', 'H'],
    title: 'genderEnum'
} as const;
