// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_ocr-ocr_endpoint
 */
export type BodyOcrOcrEndpoint = {
    /**
     * File
     */
    file?: Blob | File | null;
    /**
     * Image Url
     */
    image_url?: string | null;
};

/**
 * CandidacyPublicWithPersonalInfo
 */
export type CandidacyPublicWithPersonalInfo = {
    political_position: PoliticalPosition;
    /**
     * Position
     */
    position: number;
    /**
     * Municipality
     */
    municipality: number;
    /**
     * Id
     */
    id: string;
    candidate_personal_info: CandidatePersonalInfoPublic;
};

/**
 * CandidacyWithPersonalInfoCreate
 */
export type CandidacyWithPersonalInfoCreate = {
    municipal_candidacy: MunicipalCandidacyBase;
    candidate_personal_info: CandidatePersonalInfoBase;
};

/**
 * CandidatePersonalInfoBase
 */
export type CandidatePersonalInfoBase = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Birthdate
     */
    birthdate: string;
    gender: GenderEnum;
    /**
     * State Of Residence
     */
    state_of_residence: number;
    /**
     * Municipality Of Residence
     */
    municipality_of_residence: number;
    /**
     * Curp
     */
    curp: string;
    /**
     * Ine Valid Until
     */
    ine_valid_until: string;
    /**
     * Ine Clave Elector
     */
    ine_clave_elector: string;
    /**
     * Is Public Servant
     */
    is_public_servant: boolean;
    /**
     * Ocupation
     */
    ocupation: string;
};

/**
 * CandidatePersonalInfoPublic
 */
export type CandidatePersonalInfoPublic = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Birthdate
     */
    birthdate: string;
    gender: GenderEnum;
    /**
     * State Of Residence
     */
    state_of_residence: number;
    /**
     * Municipality Of Residence
     */
    municipality_of_residence: number;
    /**
     * Curp
     */
    curp: string;
    /**
     * Ine Valid Until
     */
    ine_valid_until: string;
    /**
     * Ine Clave Elector
     */
    ine_clave_elector: string;
    /**
     * Is Public Servant
     */
    is_public_servant: boolean;
    /**
     * Ocupation
     */
    ocupation: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * MunicipalCandidacyBase
 */
export type MunicipalCandidacyBase = {
    political_position: PoliticalPosition;
    /**
     * Position
     */
    position: number;
    /**
     * Municipality
     */
    municipality: number;
};

/**
 * PoliticalParties
 */
export type PoliticalParties = 'MC' | 'MORENA' | 'PAN' | 'PRD' | 'PRI' | 'PT';

/**
 * PoliticalPosition
 */
export type PoliticalPosition = 'Presidente' | 'Sindico' | 'Regidor';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    political_party?: PoliticalParties | null;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Municipality
     */
    municipality?: number | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    political_party?: PoliticalParties | null;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Municipality
     */
    municipality?: number | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    political_party?: PoliticalParties | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Municipality
     */
    municipality?: number | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * genderEnum
 */
export type GenderEnum = 'M' | 'H';

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type CandidaciesGetCandidaciesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Municipality
         */
        municipality: number;
    };
    url: '/api/v1/candidacies/';
};

export type CandidaciesGetCandidaciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CandidaciesGetCandidaciesError = CandidaciesGetCandidaciesErrors[keyof CandidaciesGetCandidaciesErrors];

export type CandidaciesGetCandidaciesResponses = {
    /**
     * Response Candidacies-Get Candidacies
     * Successful Response
     */
    200: Array<CandidacyPublicWithPersonalInfo>;
};

export type CandidaciesGetCandidaciesResponse = CandidaciesGetCandidaciesResponses[keyof CandidaciesGetCandidaciesResponses];

export type CandidaciesCreateCandidacyData = {
    body: CandidacyWithPersonalInfoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/candidacies/';
};

export type CandidaciesCreateCandidacyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CandidaciesCreateCandidacyError = CandidaciesCreateCandidacyErrors[keyof CandidaciesCreateCandidacyErrors];

export type CandidaciesCreateCandidacyResponses = {
    /**
     * Successful Response
     */
    200: CandidacyPublicWithPersonalInfo;
};

export type CandidaciesCreateCandidacyResponse = CandidaciesCreateCandidacyResponses[keyof CandidaciesCreateCandidacyResponses];

export type CandidaciesGetCandidacyByIdData = {
    body?: never;
    path: {
        /**
         * Candidacy Id
         */
        candidacy_id: string;
    };
    query?: never;
    url: '/api/v1/candidacies/{candidacy_id}';
};

export type CandidaciesGetCandidacyByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CandidaciesGetCandidacyByIdError = CandidaciesGetCandidacyByIdErrors[keyof CandidaciesGetCandidacyByIdErrors];

export type CandidaciesGetCandidacyByIdResponses = {
    /**
     * Successful Response
     */
    200: CandidacyPublicWithPersonalInfo;
};

export type CandidaciesGetCandidacyByIdResponse = CandidaciesGetCandidacyByIdResponses[keyof CandidaciesGetCandidacyByIdResponses];

export type OcrOcrEndpointData = {
    body?: BodyOcrOcrEndpoint;
    path?: never;
    query?: never;
    url: '/api/v1/ocr/';
};

export type OcrOcrEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OcrOcrEndpointError = OcrOcrEndpointErrors[keyof OcrOcrEndpointErrors];

export type OcrOcrEndpointResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];
